#!/usr/bin/env python3

import sys, time, argparse, subprocess, os.path
from psutil import virtual_memory

Description = """
Tool to build the multi-string BWT adapted from

   "Prefix-Free Parsing for Building Big BWTs"
   by Christina Boucher, Travis Gagie, Alan Kuhnle and Giovanni Manzini
   Proc. WABI '18 (http://drops.dagstuhl.de/opus/volltexte/2018/9304/)
   
The input file cannot contain the characters 0, 1 or 2 which are
used internally by the algorithm. The separators must be $. 
The character 0 is used as the EOF in the output BWT.
"""

# absolute path of auxiliary executables
dirname = os.path.dirname(os.path.abspath(__file__))
parse_exe       =  os.path.join(dirname, "newscan.x")
parsebwt_exe    =  os.path.join(dirname, "bwtparse")
parsebwt_exe64  =  os.path.join(dirname, "bwtparse64")
pfmultistringbwt_exe       =  os.path.join(dirname, "pfmultistringbwt.x")
pfmultistringbwt_exe64     =  os.path.join(dirname, "pfmultistringbwt64.x")
shasum_exe      =  "sha256sum"


def main():
  parser = argparse.ArgumentParser(description=Description, formatter_class=argparse.RawTextHelpFormatter)
  parser.add_argument('input', help='input file name', type=str)
  parser.add_argument('-w', '--wsize', help='sliding window size (def. 10)', default=10, type=int)
  parser.add_argument('-p', '--mod', help='hash modulus (def. 100)', default=100, type=int)
  parser.add_argument('-S',  help='compute the full Suffix Array',action='store_true')
  parser.add_argument('-D',  help='compute the full Document Array',action='store_true')
  parser.add_argument('-k',  help='keep temporary files',action='store_true')
  parser.add_argument('-v',  help='verbose',action='store_true')
  parser.add_argument('--sum', help='compute output files sha256sum',action='store_true')
  parser.add_argument('--parsing',  help='stop after the parsing phase (debug only)',action='store_true')
  args = parser.parse_args()
  if(args.S and args.D):
    print("You can either compute the full SA or the full DA, not both for now. Exiting...")
    return
    
    
  logfile_name = args.input + ".log"
  print("Sending logging messages to file:", logfile_name)
  with open(logfile_name,"a") as logfile:

    print("\n==== Execution started at", time.ctime(), file=logfile)
    logfile.flush()
    # ---------- parsing of the input file 
    start0 = start = time.time()
    command = "{exe} -w {wsize} -p {modulus} {file}".format(exe = parse_exe,
              wsize=args.wsize, modulus = args.mod, file=args.input)
    if (args.S): command += " -s"
    if (args.D): command += " -d"
    if args.v: command += " -v"
    print("==== Parsing. Command:", command)
    if(execute_command(command,logfile,logfile_name)!=True):
      return
    print("Elapsed time: {0:.4f}".format(time.time()-start))
    if args.parsing:
      # delete temporary parsing files 
      command = "rm -f {file}.parse_old {file}.last {file}.occ".format(file=args.input)
      if(execute_command(command,logfile,logfile_name)!=True):
        return
      print("==== Stopping after the parsing phase as requested")      
      return

    # ----------- computation of the BWT of the parsing
    start = time.time()
    parse_size = os.path.getsize(args.input+".parse")/4
    if(parse_size >=  (2**32-1) ):
      print("Sorry, the parse contains %d words" %  parse_size )
      print("which is more than my current limit 2^32-2")
      print("Please re-run the program with a larger modulus (currently %d)" % args.mod)
      sys.exit(1)  
    elif(parse_size >=  (2**31-1) ):
      command = "{exe} {file}".format(exe = parsebwt_exe64, file=args.input)
    else:
      command = "{exe} {file}".format(exe = parsebwt_exe, file=args.input)
    if (args.S): command += " -s"
    if (args.D): command += " -d"
    print("==== Computing BWT of parsing. Command:", command)
    if(execute_command(command,logfile,logfile_name)!=True):
      return
    print("Elapsed time: {0:.4f}".format(time.time()-start));      
    
    # ----------- compute final BWT using dictionary and BWT of parse    
    start = time.time()     
    if(os.path.getsize(args.input+".dict") >=  (2**31-4) ):
      # 64 bit version
      command = "{exe} -w {wsize} {file}".format( 
                exe = pfmultistringbwt_exe64, wsize=args.wsize, file=args.input)        
    else:  # 32 bit version
      command = "{exe} -w {wsize} {file}".format(exe = pfmultistringbwt_exe,
                wsize=args.wsize, file=args.input)

    if args.S: command += " -S"
    if args.D: command += " -D"
    
    print("==== Computing final BWT. Command:", command)
    if(execute_command(command,logfile,logfile_name)!=True):
      return
    print("Elapsed time: {0:.4f}".format(time.time()-start))      

    # ---- delete intermediate files 
    delete_temp_files(args,logfile,logfile_name)  

    # --- final report
    print("Total construction time: {0:.4f}".format(time.time()-start0))      
  

    # ---- compute sha256sum
    if args.sum:
      digest = file_digest(args.input +".bwt",logfile)
      print("BWT {exe}: {digest}".format(exe=shasum_exe, digest=digest))
      if args.S:
        digest = file_digest(args.input +".sa",logfile)
        print("SA  {exe}: {digest}".format(exe=shasum_exe, digest=digest))
      if args.D:
        digest = file_digest(args.input +".da",logfile)
        print("DA {exe}: {digest}".format(exe=shasum_exe, digest=digest))

  print("==== Done")

# delete intermediate files
def delete_temp_files(args,logfile,logfile_name):
    if args.k==False:  
      print("==== Deleting temporary files.") # no need to show the command
      command = "rm -f {file}.parse {file}.parse_old {file}.bitvector {file}.bitdict {file}.dict {file}.info {file}.map {file}.ilist {file}.occ".format(file=args.input)
      if(execute_command(command,logfile,logfile_name)!=True):
        return
      if args.S:
        command = "rm -f {file}.sai {file}.bwsai".format(file=args.input);
        if(execute_command(command,logfile,logfile_name)!=True):
          return
      if args.D:
        command = "rm -f {file}.dai {file}.bwdai".format(file=args.input);
        if(execute_command(command,logfile,logfile_name)!=True):
          return


# compute hash digest for a file 
def file_digest(name,logfile):
    try:
      hash_command = "{exe} {infile}".format(exe=shasum_exe, infile=name)
      hashsum = subprocess.check_output(hash_command.split(),stderr=logfile)
      hashsum = hashsum.decode("utf-8").split()[0]
    except:
      hashsum = "Error!" 
    return hashsum  

# execute command: return True is everything OK, False otherwise
def execute_command(command,logfile,logfile_name,env=None):
  try:
    #subprocess.run(command.split(),stdout=logfile,stderr=logfile,check=True,env=env)
    subprocess.check_call(command.split(),stdout=logfile,stderr=logfile,env=env)
  except subprocess.CalledProcessError:
    print("Error executing command line:")
    print("\t"+ command)
    print("Check log file: " + logfile_name)
    return False
  return True



if __name__ == '__main__':
    main()
